### ISSUE TITLE
org.spark_project.jetty.server.{Request, Server}

### ISSUE THREAD

**Issue by anonymous-shy** [qindongliang/streaming-offset-to-zk#1]
想问下 org.spark_project.jetty.server.{Request, Server} jetty的这几个类，这个org.spark_project是你自己的项目吧？

**Comment by qindongliang** [comment]
不是，这是spark框架自带的，可以直接用来做服务

**Comment by anonymous-shy** [comment]
是啊，我看你介绍是这么写的，那是要在pom中单独加依赖吗？因为我clone下来发下这两个类找不到依赖。

**Comment by qindongliang** [comment]
不应该啊，pom里面就是所有的依赖，你是改什么东西了吗

**Comment by anonymous-shy** [comment]
en，，，我代码里用的1.6，不行，试了下2.2，可以了。。。这算是2.x的新东西吗？还是1.x应该有对应的类估计是我找找吧。

**Comment by qindongliang** [comment]
1.x应该也有对应的，你找找
