### ISSUE TITLE
请问zk路径具体路径是？

### ISSUE THREAD

**Issue by wangzisong21** [qindongliang/streaming-offset-to-zk#2]
val zkOffsetPath="/sparkstreaming/20171128"//zk的路径

**Comment by gantts** [comment]
呵呵，自答，/latest_producer_id_block

**Comment by qindongliang** [comment]
offset在zk的路径，可以自己随便定义，没有具体要求

**Comment by wangzisong21** [comment]
请问默认是哪个路径?
/latest_producer_id_block 返回 {"version":1,"broker":177,"block_start":"2000","block_end":"2999"}
/consumers/$groupName/offsets/$topicName 返回 null
试了这两个都不行，cdh默认安装

**Comment by qindongliang** [comment]
这跟cdh没有关系呀
