### ISSUE TITLE
请问默认路径是啥，新手求解

### ISSUE THREAD

**Issue by wangzisong21** [qindongliang/streaming-offset-to-zk#3]
val zkOffsetPath="/sparkstreaming/20171128"//zk的路径

/latest_producer_id_block = {"version":1,"broker":177,"block_start":"2000","block_end":"2999"}
/consumers/$groupName/offsets/$topicName 返= null
输入这两个路径都不行，zk使用cdh默认安装，kafka离线安装配置都没改

登陆zookeeper客户端查看与kafka相关的路径有
brokers
consumers
latest_producer_id_block

这条代码接收和输出原型是什么呢
var offsets = offsetsRangesStr.split(",")//按逗号split成数组
            .map(s => s.split(":"))//按冒号拆分每个分区和偏移量
            .map { case Array(partitionStr, offsetStr) => (TopicAndPartition(topic, partitionStr.toInt) -> offsetStr.toLong) }//加工成最终的格式
            .toMap//返回一个Map

**Comment by qindongliang** [comment]
这个路径其实与kafka没有必然的联系，可以用于存储zk上任意路径，你不用去看与kafka相关的路径

**Comment by gantts** [comment]
val (offsetsRangesStrOpt, _) = ZkUtils.readDataMaybeNull(zkClient, zkOffsetPath)//从zk上读取偏移量
看你的代码有关联性啊，这一行需要输入客户端和路径，从而获取偏移量；如果我写任意路径，就获取不到偏移量了。 后面判断分区扩展也依赖这个..

**Comment by wangzisong21** [comment]
val (offsetsRangesStrOpt, _) = ZkUtils.readDataMaybeNull(zkClient, zkOffsetPath)//从zk上读取偏移量

这行代码有关联性啊，这一行需要输入客户端和路径，从而获取偏移量；如果我写任意路径，就获取不到偏移量了。 后面判断分区扩展也依赖这个..

**Comment by qindongliang** [comment]
你可以任意写路径，它会检测存在不存在，如果不存在，就代表第一次启动，它就会读取kafka分区的偏移量，创建路径并写入，如果存在就读取上次偏移量接着使用，这么说你能理解吗，意思就是这个zk路径可以任意写

**Comment by wangzisong21** [comment]
理解了老哥，感谢！
