### ISSUE TITLE
mapPartitions

### ISSUE THREAD

**Issue by qumj** [qindongliang/streaming-offset-to-zk#4]
您好！
    请教一下，您从kafka读到的数据是直接用foreachRDD，直接在drive端运行了，前期的数据处理不能用mapPartition处理吗，我前期用mapPartition处理的，结果后面的偏移量就不可以用了， val offsetsRanges = rdd.asInstanceOf[HasOffsetRanges].offsetRanges  强转不了

**Comment by qindongliang** [comment]
@qumj  RDD是分区的集合，offset必须是所有的分区同时存在才能转的，你用mapPartitions的api相当于把RDD拆分成一个个独立的partition了，因此这个方法应该用不了

**Comment by qumj** [comment]
您好！
麻烦请教下，程序运行很长时间了，突然报错   ‘Spark Streaming 'numRecords must not be negative'’，百度的时候说是偏移量有问题，读到是负的。程序运行起来一小会儿就又报这个错自动停止了。您了解大概是什么问题吗？
