### ISSUE TITLE
‘Spark Streaming 'numRecords must not be negative'’

### ISSUE THREAD

**Issue by qumj** [qindongliang/streaming-offset-to-zk#6]
您好！
麻烦请教下，程序运行很长时间了，突然报错 ‘Spark Streaming 'numRecords must not be negative'’，百度的时候说是偏移量有问题，读到是负的。程序运行起来一小会儿就又报这个错自动停止了。您了解大概是什么问题吗？

**Comment by qindongliang** [comment]
@qumj 我推测是有人删除kafka的存储文件了，不然应该是不会出现问题的，这个项目里面offset的偏移量，是我们自己维护到zk里面的，如果维护的偏移量到kafka里面去读取发现找不到了，就会大概率出现这个问题，你可以检查下是不是有人动了kafka的数据。

**Comment by qumj** [comment]
@qindongliang 谢谢您的回复！ kafka没有人动过的，一直在那儿跑着呢，突然就down掉了。把kafka topic清空重新跑，一个星期后又挂了。。。不知道是不是版本有问题还是什么

**Comment by qindongliang** [comment]
看具体的异常log，我用的版本是spark steaming2.1 + kafka 0.9.0.0
